insert into mutations (name, cost, description, mutation_type_id) values ('Adrenal Sacs', 0, 'This model is capable of overcharging itself with a short boost of adrenaline. Once per game, when the model passes an Activation test, they may select to gain an extra 2 AP for a total of 4 AP for that activation.', (select id from mutation_types where name = 'Hidden Defense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Defensive Musk', 0, 'Through methods better left unsaid, this mutant can release a nasty odor that waters the eyes and offends the palate. This model can spend 1 AP to release their musk. When this occurs, all models within 4” of the mutant must pass a Survival Test (MET/TN 10) or suffer -2 to all stat and opposed tests as if struck by a weapon with the Distracting rule.', (select id from mutation_types where name = 'Hidden Defense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Poison Secretion', 0, 'This model secretes a natural poisonous slime. All of this model‘s melee attacks, either with a melee weapon or natural weapons, counts as having the Poison weapon ability.', (select id from mutation_types where name = 'Hidden Offense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Reactive Skin', 0, 'If given time to react, this mutant may increase the natural hardness of its epidermis. This model receives an Armor Bonus (+2) against all ranged attacks that originate 8” or further away.', (select id from mutation_types where name = 'Hidden Defense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Regeneration', 0, 'This model can spontaneously heal itself, even bringing itself back from the verge of death. When this model goes out-of-action, do not remove it from the table. Instead, place it on its side and make a TN 12 Survival test at the beginning of each subsequent game turn. On a success, the model returns to play with one wound and counts as prone. This mutation can only be successfully used once per game. Note that when the model goes out-of-action, and has yet to make its Survival test, it cannot affect the tabletop in any way. It cannot claim objectives, gain Victory Points, influence other models and it can be looted, as normal. Further, an enemy model in base to base contact can spend 1 AP to coup de grace the model, which prevents the model from using this ability.', (select id from mutation_types where name = 'Hidden Defense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Retractable Spikes', 0, 'This model has retractable boney arm spikes that can be concealed. The model can spend 1 AP to count as being equipped with a masterwork light weapon that can never be disarmed or lost. This mutation counts as a one-handed weapon for Carry Capacity purposes when out, but can be retracted to allow use of the hand for 1 AP.', (select id from mutation_types where name = 'Hidden Offense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Sonic Shriek', 0, 'This model can release an ear-piercing shout that can overwhelm its target. The model may make a 16” ranged attack with the Knock Out and Small Blast weapon rules.', (select id from mutation_types where name = 'Hidden Offense'));
insert into mutations (name, cost, description, mutation_type_id) values ('Tightened Muscles', 0, 'The model’s musculature is extremely taught, enabling its limbs to move extremely fast. The model receives a +1 bonus to Agility tests and a +1 bonus to its Strength when making close combat attacks.', (select id from mutation_types where name = 'Hidden Defense'));


insert into mutations (name, cost, description, mutation_type_id) values ('Bulbous Head', 0,'This model has a head that is disproportionately large compared to the rest of its body (usually due to a little bit of extra gray matter!). The model receives a +1 bonus when taking any Intelligence Test. Additionally, once per game they may reroll a failed Will test to use a psychic ability.', (select id from mutation_types where name = 'Physical'));
insert into mutations (name, cost, description, mutation_type_id) values ('Diminutive', 0,'This mutant is smaller than the average human (typically three to four feet in height), and possess an extraordinary quickness. As such, all ranged and melee attacks directed at this model suffer a -1 penalty; however, due to their small body mass, all wound rolls against them gain a +1 bonus.', (select id from mutation_types where name = 'Physical'));
insert into mutations (name, cost, description, mutation_type_id) values ('Ghoulish', 5,'This mutant has a desiccated appearance, similar to that of a rad zombie or corpse, and is exceptionally long-lived. Neither attribute makes them popular with “smoothskins.” The model suffers a -1 to its Defense, but any time it rolls on the Survival Table, upgrade the result by one step. For example, Severely Wounded becomes Seriously Wounded, Seriously Wounded becomes Banged-Up, and so forth. Note that this mutation will not affect results of 1 or 7-9 on the table. A fumble will still result in death and a Close Call is not upgraded to a Lucky Break.', (select id from mutation_types where name = 'Physical'));
insert into mutations (name, cost, description, mutation_type_id) values ('Large Horns', 0,'This model has an impressive rack of horns atop their head, most similar to those of a bull. This model gains the Blitzer skill.', (select id from mutation_types where name = 'Physical'));
insert into mutations (name, cost, description, mutation_type_id) values ('Serpentine', 2,'Instead of normal humanoid legs, this mutant has developed a snake-like trunk and tail. If this model successfully wins a melee combat against another model, instead of making a to-wound roll, it may choose to constrict its body around their enemy. While constricted the enemy model is basically immobile, cannot take any actions that require the use of their hands, arms, or legs, and is hit automatically by any of the serpentine mutant’s subsequent melee attacks. The constricted model may use psychic powers freely and may attempt to break the mutant’s hold by spending 1 AP during its subsequent activations by passing an opposed Strength test against the serpentine model. While constricting, the serpentine mutant cannot move or take any actions other than attacking their victim with melee attacks. Should a model make a ranged attack against the serpentine mutant or its constricted victim, randomize the target, as normal.', (select id from mutation_types where name = 'Physical'));
insert into mutations (name, cost, description, mutation_type_id) values ('Tough Skin', 0,'The model is literally thick skinned or covered in dense nodules. As such, it receives an  Armor Bonus (+1).', (select id from mutation_types where name = 'Physical'));



insert into mutations (name, cost, description, mutation_type_id) values ('Puppet Master', 0,'This mutant has the insidious ability to control the minds of its enemies. Instead of rolling a normal Will test to use this power, the psychic makes an Opposed Will test against another model within 12”. If the psychic fails the test, the target suffers a -1 to its next Activation test as it shakes off its befuddlement. If the psychic wins, the target may be made to complete a 1 AP out of sequence action. If this is used to perform an attack action, the target model may use any weapon it is currently equipped with or any mutations it possesses. The psychic’s controller determines the direction of the move or the target of the attack. The model may be forced to move into base to base contact with an enemy model or walk into dangerous terrain, but they may not be forced off the table’s edge. This ability does not count as the target’s activation for this turn.', (select id from mutation_types where name = 'Psychic'));
insert into mutations (name, cost, description, mutation_type_id) values ('Invisibility', 0,'The psychic can reflect light, making itself functionally invisible from a long distance away. When this psychic ability is successfully used, any model that is 6” or farther away from this model must pass an Intelligence test if it wishes to attack the model with ranged attacks. Failure means it cannot target the invisible mutant during the current turn, but may target another model that it can see. This ability lasts until the psychic makes any type of attack, fails a Will test, or fails to maintain concentration. To maintain concentration, the model must pass a Will test (MET/ TN10) at the start of their activation. This does not cost AP or counts as using a psychic ability. If they fail this ability is lost. ', (select id from mutation_types where name = 'Psychic'));
insert into mutations (name, cost, description, mutation_type_id) values ('Telekinetic Push', 0,'The psychic can send waves of psychic energy through the earth at high speeds, pushing its enemies about as if they were playthings. Treat this as an 18” ranged attack. If successful, the target and all models within 4” of it must pass a Strength test (MET/TN 10) or be knocked prone.', (select id from mutation_types where name = 'Psychic'));
insert into mutations (name, cost, description, mutation_type_id) values ('Psychic Boost', 0,'The psychic can slow the flow of time, giving the outward appearance of moving at super speed. If successful, the psychic may target any model within 6”, including itself. The target gains a +1 to its Move, Melee, and Mettle stats until the Clean-up Phase of the current game turn, or gains a +3 bonus to its next Activation test. ', (select id from mutation_types where name = 'Psychic'));

update mutations set description = 'The mutant’s mind can resist the pull of gravity and allow themselves or another to float for a short time. If the psychic test is successful, the psychic or another friendly model within 12” may gain the Hover ability. This ability remains until the psychic model chooses to end it or the psychic fails any type of Will test. A psychic may only levitate one model at a time.' where name = 'Levitation';
update mutations set description = 'The psychic can throw a bolt of pure energy towards its enemy. If successful, treat it as 24” ranged attack with a Strength of 7 and the Close Range weapon rule. If the psychic has already used this power once this game turn, or if the psychic cannot physically draw line of sight to the target, the attack suffers a -2 Strength penalty and loses the Close Range rule.' where name = 'Psychic Bolt';

